### ISSUE TITLE
Compound bot not able to handle bot with no safetyorders

### ISSUE THREAD

**Issue by bramjekel** [cyberjunky/3commas-cyber-bots#107]
The latest version of the compound.py bot helper is not able to compound the earned profit to the BO if there are no SOs.

I have manually added some lines of code to the python script for work-around this.

I have changed this code starting on line 545:

funds_so_needed = safety_order_volume
total_so_funds = safety_order_volume
if max_safety_orders > 1:
    for i in range(1, max_safety_orders):
        funds_so_needed *= float(martingale_volume_coefficient)
        total_so_funds += funds_so_needed`

To:

funds_so_needed = safety_order_volume
total_so_funds = safety_order_volume
if max_safety_orders < 1:
    total_so_funds = 0
if max_safety_orders > 1:
    for i in range(1, max_safety_orders):
        funds_so_needed *= float(martingale_volume_coefficient)
        total_so_funds += funds_so_needed

**Comment by cyberjunky** [comment]
@bramjekel Bram, thanks! I have added your fix to latest code, maybe you are able to check it? 
I will close this, if something isn't right please reopen.
