### ISSUE TITLE
Combine Altrank and Galaxy Score / Coinmarketcap

### ISSUE THREAD

**Issue by frontero** [cyberjunky/3commas-cyber-bots#108]
Is it possible to combine the Altrank score and Galaxy Score / Coinmarketcap? So to add a coin if the altrank score is < 50 and the Galaxy Score < 100 i.e.?

**Comment by rthepen** [comment]
Hoi,  soon you will need to hold lunr to use the api

**Comment by frontero** [comment]
> 

How many lunr do you need to hold?

**Comment by Gh61** [comment]
Coinmarket cap is not part of the LunarCrush API - so it would be unnecessarily complicated to add another call to another API to bots.

GalaxyScore is ranked oposite of altrank. The bigger the better.
I have been planing to add minGalaxyScore parameter to altrank bot. But as I watched the corelation between GS and AltRank, it is not my priority anymore.

**Comment by frontero** [comment]
@Gh61 are you saying that there is no relation between between the Galaxy Score and Altrank?

The reason why I would like to add the Coinmarketcap ranking score is that it would buy shitty coins that are for example above 500.

**Comment by Gh61** [comment]
No, I am saying the exact opposite - in my observings, if some coin is high in altrank, it has pretty high Galaxy Score (and if not, it will follow during a few minutes).

I understand your coin market cap proposed strategy, but bot based on altrank or galaxy score is mostly about Volatility trading, where you don't care if it's shit coin or some strong altcoin.

**Comment by rthepen** [comment]
> > 
> 
> 
> 
> How many lunr do you need to hold?

500 and also pay some Lunr to use it, but that's not clear. 

I'm working to build my own ranking Including ta, social activity and on chain analysis.

**Comment by cyberjunky** [comment]
Altrank and Galaxyscore coins are just that, building checkis against coinmaketcap is possible, but it requires at least 4 extra ini file settings, and whats next... Maybe later I build a combination of all of them but for now closing this request. FOr now you can block shitcoins using local or 3commas blacklist, or 24h volume threshold.
