### ISSUE TITLE
Start a deal one time when a coin enters the top 10 altrank

### ISSUE THREAD

**Issue by frontero** [cyberjunky/3commas-cyber-bots#109]
When a coin enters the top 10 or top x of the altrank score I want that automatically a deal starts in 3commas once. So not keep starting the deals over and over once it is in the top 10 altrank score. When it goes above, lets say the altrank score of 50 and enters the top 10 again then it may start a new deal in 3commas. Would that be possible?

**Comment by cyberjunky** [comment]
This involves adding a database to record if coins where in top 10 already or not, this would over complicate this script.
