### ISSUE TITLE
Telegram/apprise

### ISSUE THREAD

**Issue by Ckoz1** [cyberjunky/3commas-cyber-bots#110]
Do yoU have an example of how to set up telegram and apprise.  Keep getting a no apprise module error 
Thanks 

**Expected behavior**

**Screenshots**

**Environment:**
 - Python version: python3 -V
 - Operating System: uname -a
 - Version of software [e.g. 0.6.1]:

**Additional context**

**Comment by cyberjunky** [comment]
'No module error' usually means you don't have all the python package requirements successfully installed, have you tried running this ones?
```
pip3 install -r requirements.txt
```

**Comment by cyberjunky** [comment]
@Ckoz1 closing for now, if you still have issue, let me know
