### ISSUE TITLE
Logging.py utf8 error

### ISSUE THREAD

**Issue by bramjekel** [cyberjunky/3commas-cyber-bots#111]
Logging.py is giving a UTF8 error because of the bitcoin character. This can be resolved by adding ", encoding='utf-8'" to line 156, like below.

        # Log to file and rotate if needed
        file_handle = TimedRotatingFileHandler(
            filename=f"{self.datadir}/logs/{self.program}.log", backupCount=logstokeep, encoding='utf-8'
        )
        file_handle.setFormatter(formatter)
        self.my_logger.addHandler(file_handle)

**Comment by cyberjunky** [comment]
Thanks @bramjekel, will add patches soon!

**Comment by cyberjunky** [comment]
Added, maybe you can have a check? Thanks!

**Comment by cyberjunky** [comment]
If still not ok, please (re)open
