### ISSUE TITLE
Add maxaltrankscore in the botassistexplorer script

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#115]
Hello!
Could you add "maxaltrankscore" in the botassistexplorer script in the future when you can?

off: you could register in brave to receive bat token as a tip, in github I see many users who can receive those tips but I see that you are not registered. It would be another way to collaborate.

thanks

**Comment by dangalv** [comment]
If I work from altrank.py and other similar scripts there is a problem that the bot cannot start if I activate " allowbotstopstart ". As much as the currency is in the first place and I put these parameters: altrankscore: 1 numberofpairs: 1 and originalmaxdeals = 1 the bot cannot turn on

**Comment by amargedon** [comment]
I can have a look at the max altrank score as in the previous commit the handling of all columns has been improved (and are now available to filter on).

**Comment by amargedon** [comment]
And the option is added, pull request is open and waiting for @cyberjunky to be merged. Default value is set to 1500 (same as in altrank.py), which you can change afterwards off course.

**Comment by dangalv** [comment]
> I can have a look at the max altrank score as in the previous commit the handling of all columns has been improved (and are now available to filter on).

Thanks again for joining the thread, look I think it's a good idea to filter the ranking of the coins regardless if that coin is the first in the column, since it does not guarantee that that coin will be the first in the lunarcrush global list, it can be the first of the list of the exchange that I use but not be the number 1 of global altrank.
Oh and another thing I know I could use altrank instead of this script but a good reason I see in using this script is that it would be a good alternative to the original LC API since it may not be free anymore, I just hope 3ctools survives too

**Comment by amargedon** [comment]
> > I can have a look at the max altrank score as in the previous commit the handling of all columns has been improved (and are now available to filter on).
> 
> Thanks again for joining the thread, look I think it's a good idea to filter the ranking of the coins regardless if that coin is the first in the column, since it does not guarantee that that coin will be the first in the lunarcrush global list, it can be the first of the list of the exchange that I use but not be the number 1 of global altrank. Oh and another thing I know I could use altrank instead of this script but a good reason I see in using this script is that it would be a good alternative to the original LC API since it may not be free anymore, I just hope 3ctools survives too

Not sure if I understand correctly. 3C-tools does already sort the list (https://www.3c-tools.com/markets/bot-assist-explorer?list=binance_spot_busd_alt_rank for example) on alt-rank score so if you get the top one it will be the highest alt-rank score. Does not need to be alt-rank score 1, so retrieving only 1 coin and having maxaltrankscore on 1 will enable you the get the top alt-rank coin if it's in the list.

**Comment by dangalv** [comment]
> > > I can have a look at the max altrank score as in the previous commit the handling of all columns has been improved (and are now available to filter on).
> > 
> > 
> > Thanks again for joining the thread, look I think it's a good idea to filter the ranking of the coins regardless if that coin is the first in the column, since it does not guarantee that that coin will be the first in the lunarcrush global list, it can be the first of the list of the exchange that I use but not be the number 1 of global altrank. Oh and another thing I know I could use altrank instead of this script but a good reason I see in using this script is that it would be a good alternative to the original LC API since it may not be free anymore, I just hope 3ctools survives too
> 
> Not sure if I understand correctly. 3C-tools does already sort the list (https://www.3c-tools.com/markets/bot-assist-explorer?list=binance_spot_busd_alt_rank for example) on alt-rank score so if you get the top one it will be the highest alt-rank score. Does not need to be alt-rank score 1, so retrieving only 1 coin and having maxaltrankscore on 1 will enable you the get the top alt-rank coin if it's in the list.

Look I leave an example so you can understand me:
suppose that global altrank is VRA in the first position, but VRA does not exist in Binance futures, so XRP is in global altrank 2 but it is first in the list which I do not care about, I just want the bot to work with the first currency of the global altrank, which is exactly what it shows in the "alt-rank" part of the list

In this example case can clearly occur if the first coin in the list is not reached by the top of the global list.

![Captura de pantalla 2022-04-15 071213](https://user-images.githubusercontent.com/97088068/163560374-a1550af2-5e07-4dcb-a283-599d837b3ee1.png)

**Comment by amargedon** [comment]
But, if you want to have coins that are available in Binance Futures, and want to have only the first one, then use the following list: https://www.3c-tools.com/markets/bot-assist-explorer?list=binance_futures_usdt_alt_rank. Set the start- and end- number of the botassistexplorer.py script to 1 and you only get the first one?

**Comment by dangalv** [comment]
> But, if you want to have coins that are available in Binance Futures, and want to have only the first one, then use the following list: https://www.3c-tools.com/markets/bot-assist-explorer?list=binance_futures_usdt_alt_rank. Set the start- and end- number of the botassistexplorer.py script to 1 and you only get the first one?

The position of the list does not interest me really, but the position of the altrank score does, there may be cases that the first coin of that list (binance futures) does not correspond to the first coin of the number one position in the altrank "global". As I explained in the previous example.

But never mind mate, thanks for modifying the altrank script from the other thread, this "3c-tools" script is just an alternative to a possible lunarcrush free API shutdown, but in the future 3c-tools might be the one to save the day not having the free version of LC.

**Comment by dangalv** [comment]
Added in the last update, thanks guys :)

**Comment by dangalv** [comment]
I leave a possible feature that could be brought from other scripts and improve the bootassistexplorer script.
For some reason in certain custom setup "numberofpairs" is missing. If you want reasons I can explain why this feature is missing.

I didn't know whether to open another thread but if you read it it would be a good addition to future updates, sorry for the inconvenience.

Thanks!

**Comment by dangalv** [comment]
I leave a possible feature that could be brought from other scripts and improve the bootassistexplorer script.
For some reason in certain custom configuration "numberofpairs" is missing. If you want reasons I can explain why this feature is missing.

I didn't know whether to open another thread but if you read it it would be a good addition to future updates, sorry for the inconvenience.

Thanks!
