### ISSUE TITLE
I can't get the top coin to turn on the bot

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#116]
I don't understand how to make the lunarcrush top coin make the bot turn on.
My setup:

![image](https://user-images.githubusercontent.com/97088068/163480156-3b40ec67-b4aa-41ea-aaf4-f2ed5f39d613.png)

the bot changes the currency but does not turn on the bot:
![image](https://user-images.githubusercontent.com/97088068/163480249-762686f3-959a-478e-a2b8-80d7a795edf2.png)

![image](https://user-images.githubusercontent.com/97088068/163480329-3949de57-d1d3-4c92-b196-da0aab7b928d.png)

any help please?

**Comment by pvdochtend** [comment]
If I'm correct, that's how the scripts works. It only changes the pairs/coins but not that status of the bot. 

You can turn it in manually.

**Comment by dangalv** [comment]
> If I'm correct, that's how the scripts works. It only changes the pairs/coins but not that status of the bot.
> 
> You can turn it in manually.

The last update of the bothelper allows to turn on/off the bot  automatically if there is no coin to trade in a certain range. (see allowbotstopstart condition)
Even if enabled this feature "allowbotstopstart" automatically turns off if I manually turn the bot on.

**Comment by amargedon** [comment]
I do assume you are using the botassistexplorer.py script? Because maxaltrankscore and comment are not entries used by the configuration, so it seems at least your config is a mix of two different scripts.

However, that should not be an issue and is just something I notice. The last update of the botassistexplorer script will stop/start the bot and I just tested with a bot of mine and saw it's working.

Main question for you; what does the logging tell (you can enable the Debug = True to get more insight)? What is your bot min 24h volume set to, and is the specific coin above that? 3C will not allow a bot without any pair set, so the case I'm thinking about is the following: the number 1 coin is below your 24h volume limit, meaning zero coins to trade, meaning the bot should not be started or stopped if it's started (and 3C will show this coin, as we cannot remove it as 3C does not allow empty pairs).

**Comment by dangalv** [comment]
> I do assume you are using the botassistexplorer.py script? Because maxaltrankscore and comment are not entries used by the configuration, so it seems at least your config is a mix of two different scripts.
> 
> However, that should not be an issue and is just something I notice. The last update of the botassistexplorer script will stop/start the bot and I just tested with a bot of mine and saw it's working.
> 
> Main question for you; what does the logging tell (you can enable the Debug = True to get more insight)? What is your bot min 24h volume set to, and is the specific coin above that? 3C will not allow a bot without any pair set, so the case I'm thinking about is the following: the number 1 coin is below your 24h volume limit, meaning zero coins to trade, meaning the bot should not be started or stopped if it's started (and 3C will show this coin, as we cannot remove it as 3C does not allow empty pairs).

Hello, thanks for answering, I will try to speak to you from a translator, I hope you understand me.
I will explain the case to you in more depth. In this case, I used the "altrank.py" script. I don't use a volume limit, I just want to trade the first coin in the lunarcrush altrank list, if none exist the bot will stop. As with the configuration established at the beginning of this thread, nor with other configurations that I tried, I could not get the bot to wake up when that condition was met.

**Comment by amargedon** [comment]
Thanks for your reply! Oke, so you are using altrank.py and no volume filter; clear.

In your configuration; lc-fetchlimit is set to 10. I think the data which is retrieved is the same as shown on this page: https://legacy.lunarcrush.com/markets?rpp=50. Looking at the top 10, there is no coin with an altrank score of 1...The coin with an altrank score of 1 (XRP at moment of writing) is at position 21 which is outside the configured fetchlimit of 10. 

So, did you try to increase lc-fetchlimit to something like 25 of 50 so the number 1 altrank score can be found in a larger dataset?

**Comment by dangalv** [comment]
> 



> Thanks for your reply! Oke, so you are using altrank.py and no volume filter; clear.
> 
> In your configuration; lc-fetchlimit is set to 10. I think the data which is retrieved is the same as shown on this page: https://legacy.lunarcrush.com/markets?rpp=50. Looking at the top 10, there is no coin with an altrank score of 1...The coin with an altrank score of 1 (XRP at moment of writing) is at position 21 which is outside the configured fetchlimit of 10.
> 
> And, as a result, there are no coins available by the script for trading so the bot will not be enabled.
> 
> So, did you try to increase lc-fetchlimit to something like 25 of 50 so the number 1 altrank score can be found in a larger dataset?

yes, it may be that now there is no coin to place first in the LC list, but in the example I gave a few hours ago KNC was first in the list and the fetchlimit was set to 10, I suppose that the bothelper could read that coin without problems to make it work in binance futures contracts, which is the exchange where I test it, I even noticed how the currency changed automatically but the bot did not turn on :( and if I manually turned on the bot from 3commas, the "bothelper" would I took care of turning it off later :'

  (For clarification, fetchlimit is one of many data that I modified to see if I could find a correct setup, I put it in: 1, 10 or default (150), without ever making the bot start when the coin was first in the list of the altrank.)

**Comment by amargedon** [comment]
Oke, will in that case I need more logging to investige further in order to determine what is going on. 

Can you please provide logging (with Debug = True set in the configuration) when this situation happens again? Hopefully, with this logging we get more details of what is going on.

**Comment by dangalv** [comment]
> Oke, will in that case I need more logging to investige further in order to determine what is going on.
> 
> Can you please provide logging (with Debug = True set in the configuration) when this situation happens again? Hopefully, with this logging we get more details of what is going on.

[altrank.log.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/8495335/altrank.log.txt)

there are the attempts of this day

**Comment by amargedon** [comment]
[altrank.py.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/8495425/altrank.py.txt)

In your case, the max number of deals is already 1 and the number of new pairs is also 1. The stop/start of the bot was only checked when the max number of deals would change, but that is not happening in your case. So, I have changed this check by looking at the number of pairs; if the valid number of pairs is 0 bot should stop, if valid number is 1 or more the bot should start (if it's stopped).

Can you try with the attached updated script? Please remove the ".txt" so the extension is ".py" only (was not allowed to upload the file with .py...).

**Comment by dangalv** [comment]
> [altrank.py.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/8495425/altrank.py.txt)
> 
> In your case, the max number of deals is already 1 and the number of new pairs is also 1. The stop/start of the bot was only checked when the max number of deals would change, but that is not happening in your case. So, I have changed this check by looking at the number of pairs; if the valid number of pairs is 0 bot should stop, if valid number is 1 or more the bot should start (if it's stopped).
> 
> Can you try with the attached updated script? Please remove the ".txt" so the extension is ".py" only (was not allowed to upload the file with .py...).

Woow dude! With that script, it perfectly turns on the bot now that there is a coin in the top available in the exchange :) we will see how it continues to work in the future when there is no coin available from the exchange in the first position. I will be eternally grateful to you!

**Comment by amargedon** [comment]
Thanks for the feedback, and I'm happy the script is working for you! I will commit this change as for my bots it still is working, so after a new merge by @cyberjunky you can use the script from the repository again.

**Comment by dangalv** [comment]
> Thanks for the feedback, and I'm happy the script is working for you! I will commit this change as for my bots it still is working, so after a new merge by @cyberjunky you can use the script from the repository again.

Great! Thanks again! 

As an addition that maybe you should see later is for the other scripts like the galaxyscore script, it has a similar problem not turning on when setting parameters like mingalaxyscore = 74 (example) or other parameters. But I guess it will be easy after fixing this code, I still don't want to bother you anymore, you've made my day with the altrank thing, I should consider opening a way to collaborate by donating something for your help, I have yet to help those who help me like the creator of the bot and good people like you.
