### ISSUE TITLE
Compound script not taking leverage into account

### ISSUE THREAD

**Issue by bramjekel** [cyberjunky/3commas-cyber-bots#121]
Could be considered as a bug if you use leverage so therefore logged as a bug instead of an enhancement request :-). 

Compound.py is not increasing the BO and SO volumes with taking into account the set leverage custom value of the bot.

In the compound_bot function section 'if profit_sum:' condition on line 535 the following needs to added to retreive the set leverage customer value from the bot:
        leverage_custom_value = float(
            thebot["leverage_custom_value"]
        )

Then the BO and SO volumes need to be multiplied with the leverage custom value:
        bo_profit = (((profit_sum * bo_percentage) / 100) / max_active_deals) * leverage_custom_value

SO profit does not need adjustment as it calculated based on the BO profit.

**Comment by bramjekel** [comment]
Just realized that I have not taking into account bots without leverage so code now gives some errors. Working on fixes. Expect update in coming days.

**Comment by cyberjunky** [comment]
Thank you in advance!

**Comment by bramjekel** [comment]
[compound.zip](https://github.com/cyberjunky/3commas-cyber-bots/files/8585370/compound.zip)

Attached the adjusted compound.py file. I have modified several parts to enable compounding for leveraged bots.

I have also made some additional adjustments for my previous logged issue with bots with no SOs (see [https://github.com/cyberjunky/3commas-cyber-bots/issues/107](url) ).

**Comment by cyberjunky** [comment]
Thanks Bram! I merged your code into the repository

**Comment by bramjekel** [comment]
@cyberjunky No problem. I love the work you have put into it, it's a small thing for me to help.
