### ISSUE TITLE
Maximum Active Deals in 3commas not changed

### ISSUE THREAD

**Issue by Janc63** [cyberjunky/3commas-cyber-bots#124]
I am not so familiar with the use of Github so I appologize in case I am not approaching you in the right way. 

It's about the bot altrank.py and galaxyscore bot.
I have added the following lines in the .ini files:

originalmaxdeals = 6
allowmaxdealchange = True
allowbotstopstart = True

However, if the amount of available coinpairs become less then the initial amount of max deals, normaly the allowmaxdealchange option should be activated if I'm right.  
Unfortunately it is NOT responding and the bot may produce an error message. 
I have searched over here if there is an update on it but I could not find it to be honest. 

Would it be possible to let me know how I can fix this? I am not a trained Python programmer but maybe if you guide me or show me where I can find an update, it would be much appreciated. 

Best regards, 

Jan Ceulemans
ceulemans.jan@gmail.com

**Comment by cyberjunky** [comment]
Closing, stale ticket, no response, cannot reproduce
