### ISSUE TITLE
[Question] Will the "trailingstoploss_tp.py" work with Futures Long and Short leveraged bots?

### ISSUE THREAD

**Issue by wrone** [cyberjunky/3commas-cyber-bots#129]
Hey!

I'm running long and short leveraged bots. I was using trailingstoploss_tp for spot bots but will it work with the leveraged bots? I see that there is a "Futures trailing stoploss bot helper named trailingstoploss.py", but it is not as flexible as trailingstoploss_tp.py, right? You can't configure multiple "activation-percentage" and "initial-stoploss-percentage".

**Comment by amargedon** [comment]
Not sure, to be honest. I've written the script and only used it on the spot market. 

However, trailingstoploss_tp.py is based on trailingstoploss.py and the very core of the code (behaviour) is the same; calculate SL percentage and update deal at 3Commas. As far as I know leverage it's still a deal with an opening price, on which you can calculate SL and TP level (which is what the script does).

So my guess would be that it should work. Would recommend you to first run it on paperaccount before switching to real, to make sure my guess is right.

**Comment by wrone** [comment]
Hi @amargedon!

I'm running it on my real account with small amounts - as of now, looks ok.

Thanks for answering and thanks for sharing this script!
