### ISSUE TITLE
legacy.lunarcrush.com no longer accessible to generate the API key

### ISSUE THREAD

**Issue by judasbenhur** [cyberjunky/3commas-cyber-bots#130]
As outlined in the readme its no longer possible to generate an API key for lunarcrush because legacy.lunarcrush.com redirects to lunarcrush.com. Apparently they are working on a new API access that will be pay to use. 

Any alternative or way to fix this in the meantime? Maybe this could be alternative? https://pypi.org/project/lunarcrush/

**Comment by cyberjunky** [comment]
My script doesn't need a API key either, just leave it at default value, don't know when this stops to work though
