### ISSUE TITLE
Disbalance when lost deals in compound script

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#147]
Hello there! 

**Describe the bug**
Compound script does not adjust values well when a deal is lost on stop loss condition or timeout market sell.
(For clarification, the script does the process perfectly when deals are in profit)

**To Reproduce**

I simply run the compound script and when a deal loses I calculate the compound value that should lower the BO/SO values is still considerably higher

**Expected behavior**
If for example in a bot that the BO/SO is 20 USDT and I won 10 USDT and then I lost them, the BO/SO should approach 20 dollars again I think. This is not happening correctly

**Screenshots**

To confirm my manual calculation and realize that there is a calculation error, I do the following

values miscalculated:
![compound1](https://user-images.githubusercontent.com/97088068/196013820-6faffac7-55ce-4e4b-9734-8c38e9594120.png)

I reset the original BO/SO values and delete the sqlite3 file:
![compound3](https://user-images.githubusercontent.com/97088068/196013862-bb992bce-6ac1-4ab5-9888-08db238b1495.png)

Then I reset script to apply changes to readjust the values which is close to my manual calculation:
![compound4](https://user-images.githubusercontent.com/97088068/196013901-2f95513f-d00c-445b-bba2-1a042148e92e.png)

In few words:
The calculated values without restarting the script is:  BO: 11.71~ / SO: 5.85~
The recalculated values doing the complete reset: BO: 11.05~  / SO: 5.52~

**Environment:**
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1020-aws x86_64)
Python 3.10.6
I use the last compound update (13th october 2022)

**Additional context**
I only report this possible error, it's not urgent, I opened a thread with another problem and they told me to report it in a specific thread.
Thanks for your work guys. Cheers!

**Comment by dangalv** [comment]
Rather, I am noticing with the new script that it does not apply the changes when it loses due to SL. Restart several times, the new value that drops is the correct one since I did the deletion of the sql db of the compound script and it gave me what it says 7.45 there
But the problem that does not apply the values when there is a loss in the bot

![image](https://user-images.githubusercontent.com/97088068/196026572-5b7cbf4c-e2cd-422e-a7bd-2bd494ba9fa0.png)

I will continue to closely analyze the scripts both the old and the new one

**Comment by amargedon** [comment]
Thanks for the seperate report and your (extended) information. I do recognize the compound script is not perfect, and with a recent change we broke some functionality is my conclusion based on your data. We did add some checks and these checks assume the BO will only increase, so decreasing after a loss is no longer possible.

@brhahlen and me are looking into the option to make the script more accurate because there is some rounding functionality used. I will also discuss that we need to have the decreasing BO option back!

Stay tuned, more information and update(s) will follow although I cannot promise any timeline.

**Comment by dangalv** [comment]
> Thanks for the seperate report and your (extended) information. I do recognize the compound script is not perfect, and with a recent change we broke some functionality is my conclusion based on your data. We did add some checks and these checks assume the BO will only increase, so decreasing after a loss is no longer possible.
> 
> @brhahlen and me are looking into the option to make the script more accurate because there is some rounding functionality used. I will also discuss that we need to have the decreasing BO option back!
> 
> Stay tuned, more information and update(s) will follow although I cannot promise any timeline.

Thanks fellow armageddon for responding.
As I said before in the other thread, I know what it must cost to make these scripts and we appreciate your good will in such contributions.
I am Testing the old and new script, but I was parsing the old one (since this works somewhat better to discount) and sometimes it is not necessary to restart it (delete sql db), I think the problem is when there is a deal that takes time to close and the other deals are closed faster, when one of the fast deals is usually closed at a loss, that is where the total count of the compound script is desynchronized and there ends up being an imbalance.
I don't know if it would be a bad idea, said from my ignorance, that the bot can reread the PnL in case of a negative deal (or not) and readjust the values ​​that correspond to the total PnL? That it takes the starting value of the bot, for example 10 usdt and from that base, execute a rereading of the PnL, this as an additional option, does not mean that this option is executed by default, but in special cases like these and that it be enabled by the user as "force reread compound pnl"
Take it as an idea, I don't know if it is feasible to execute it.
Any notes I have to tell you about the script, I'll be sharing.
Thank you

**Comment by brhahlen** [comment]
@dangalv My apologies for the delay in responding. Things have been a bit busy here and there.
I've just submitted an update to my PR, that should (hopefully) fix the negative compounding.

I've tested it out with a bot that has some losses as well, and it seems to work fine, but would be good if you could check as well (after @amargedon has approved the PR :) )

**Comment by dangalv** [comment]
> @dangalv My apologies for the delay in responding. Things have been a bit busy here and there. I've just submitted an update to my PR, that should (hopefully) fix the negative compounding.
> 
> I've tested it out with a bot that has some losses as well, and it seems to work fine, but would be good if you could check as well (after @amargedon has approved the PR :) )

Thanks you very much for your work @brhahlen :)  I'll take a look later and give my opinion if necessary

**Comment by amargedon** [comment]
I just merged PR #157 into the repo so the updated script is available for testing by you.

**Comment by dangalv** [comment]
> I just merged PR #157 into the repo so the updated script is available for testing by you.

Thank you friends for your commitment
