### ISSUE TITLE
Script bot helper error 

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#153]
Hello! 

I only leave a possible error with the helper scripts with the new update (also in case any user thinks about updating), in my case I usebootsistexplorer but I did not try the altrank or galaxy script since since I returned to the previous compilation, but I also suppose that the same error case can occur since those scripts were also updated
 I leave the catch.

![197363762-f1befd72-e1cc-4091-bae6-bc8c542d5d53](https://user-images.githubusercontent.com/97088068/197363952-a787c919-467f-40c3-a4c8-557207527941.png)

It can also be an error of the new files that were updated from the "helper" folder since when I returned to the previous "botassistexplorer" script it still did not work and then I replaced all the files in the helper folder and it worked again.

Always keep a copy of the previous script in case you have any problems with the update.

Cheers

**Comment by sirjimjones** [comment]
i have the same issue @cyberjunky

**Comment by cyberjunky** [comment]
@dangalv @sirjimjones The helper files got a new dependency named 'cloudscraper' Simply install it by running this ones (not bad to do after an update anyway, since it can update certain modules too)
```
pip3 install -r requirements.txt
```

**Comment by sirjimjones** [comment]
Thanks a lot, now its working! I wasn't aware how to properly perform an update. I was simply doing a "git pull origin main". Maybe put a line in the README how to update the script in case someone else is facing the same issue? I would highly appreciate :)

**Comment by cyberjunky** [comment]
It was there all along: ;-)

https://github.com/cyberjunky/3commas-cyber-bots#download-and-install
