### ISSUE TITLE
Bug or API issues? (altrank / galaxyscore script) - Reopened

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#159]
Hi guys, sorry to be annoying again. I'm on your side 
But there is an error that I don't know if it's already an API error or a bug in the altrank and galaxyscore script encoding
I haven't used these scripts for a long time since I used botassistexplorer but for some reason this script got stuck and doesn't renew the coins in the altrank list (3c-tools error, not the script)
I did a clean install of the script installing helper requirements and the error persists.

![image](https://user-images.githubusercontent.com/97088068/199402084-98731bc9-7c76-4ab5-bffc-034c19e46a35.png)

04:45 ~/3commas-cyber-bots (main)$ ./galaxyscore.py                                                                                                                                                              
2022-11-02 04:45:44 - galaxyscore - INFO - 3C Cyber Bot-Helper galaxyscore
2022-11-02 04:45:44 - galaxyscore - INFO - Started on Wednesday 04:45:44 2022-11-02
2022-11-02 04:45:44 - galaxyscore - INFO - Notifications are disabled
2022-11-02 04:45:44 - galaxyscore - INFO - Created example config file '/home/droidg/3commas-cyber-bots/galaxyscore.ini', edit it and restart the program
04:45 ~/3commas-cyber-bots (main)$ ^C
04:46 ~/3commas-cyber-bots (main)$ ./galaxyscore.py
2022-11-02 05:47:11 - galaxyscore - INFO - 3C Cyber Bot-Helper galaxyscore
2022-11-02 05:47:11 - galaxyscore - INFO - Started on Wednesday 05:47:11 2022-11-02
2022-11-02 05:47:11 - galaxyscore - INFO - Notifications are disabled
2022-11-02 05:47:11 - galaxyscore - INFO - Loaded configuration from '/home/droidg/3commas-cyber-bots/galaxyscore.ini'
2022-11-02 05:47:11 - galaxyscore - INFO - Reloaded configuration from '/home/droidg/3commas-cyber-bots/galaxyscore.ini'
2022-11-02 05:47:11 - galaxyscore - INFO - Fetched 3Commas pairs blacklist OK (0 pairs)
2022-11-02 05:47:11 - galaxyscore - INFO - Fetched 3Commas price OK (20522.48)
Traceback (most recent call last):
  File "/home/droidg/3commas-cyber-bots/./galaxyscore.py", line 372, in <module>
    usdtbtcprice = get_threecommas_btcusd(logger, api)
  File "/home/droidg/3commas-cyber-bots/helpers/threecommas.py", line 74, in get_threecommas_btcusd
    if isnan(price):
TypeError: must be real number, not str
04:47 ~/3commas-cyber-bots (main)$ ./altrank.py                                                                                                                                                                  
2022-11-02 04:48:25 - altrank - INFO - 3C Cyber Bot-Helper altrank
2022-11-02 04:48:25 - altrank - INFO - Started on Wednesday 04:48:25 2022-11-02
2022-11-02 04:48:25 - altrank - INFO - Notifications are disabled
2022-11-02 04:48:25 - altrank - INFO - Created example config file '/home/droidg/3commas-cyber-bots/altrank.ini', edit it and restart the program
04:48 ~/3commas-cyber-bots (main)$ ./altrank.py
2022-11-02 05:50:35 - altrank - INFO - 3C Cyber Bot-Helper altrank
2022-11-02 05:50:35 - altrank - INFO - Started on Wednesday 05:50:35 2022-11-02
2022-11-02 05:50:35 - altrank - INFO - Notifications are disabled
2022-11-02 05:50:35 - altrank - INFO - Loaded configuration from '/home/droidg/3commas-cyber-bots/altrank.ini'
2022-11-02 05:50:35 - altrank - INFO - Reloaded configuration from '/home/droidg/3commas-cyber-bots/altrank.ini'
2022-11-02 05:50:35 - altrank - INFO - Fetched 3Commas pairs blacklist OK (0 pairs)
2022-11-02 05:50:35 - altrank - INFO - Fetched 3Commas price OK (20520.29)
Traceback (most recent call last):
  File "/home/droidg/3commas-cyber-bots/./altrank.py", line 360, in <module>
    usdtbtcprice = get_threecommas_btcusd(logger, api)
  File "/home/droidg/3commas-cyber-bots/helpers/threecommas.py", line 74, in get_threecommas_btcusd
    if isnan(price):
TypeError: must be real number, not str
04:50 ~/3commas-cyber-bots (main)$

Thank you and sorry for my inconvenience. Cheers

**Comment by dangalv** [comment]
Unfortunately the free lunarcrush api was revoked, so botassistexplorer (3c-tool) affected it as well. I guess there is no API error

**Comment by dangalv** [comment]
Update: I bought the API for one day from lunarcrush and the script error is the same 😔

**Comment by thematikma** [comment]
The api v3 uses different endpoints. I reckon changing all lc scripts will be necessary.

**Comment by amargedon** [comment]
Thanks, just replied to the other issue as well. Yes, these scripts need some work to match the new endpoint. Will look into this, not sure when however.

**Comment by dangalv** [comment]
> Thanks, just replied to the other issue as well. Yes, these scripts need some work to match the new endpoint. Will look into this, not sure when however.

Nice thanks!

**Comment by cyberjunky** [comment]
@dangalv @thematikma I have updated some code, using my new api3 key I got so far...
I'm still recovering from illness, maybe you can try and give some results...
```2022-11-06 13:26:40 - altrank - ERROR - Fetching LunarCrush data failed 500 {"error":"Error: You must have at least $1 USD in your LunarCrush payments account to use this endpoint."}
```

**Comment by thematikma** [comment]
@cyberjunky @dangalv @amargedon Many thanks for your efforts! I will have a try later and post results.
And a speedy recovery to @cyberjunky

**Comment by cyberjunky** [comment]
It doesn't look to me API is free for any /coins calls (you need at least 240 credits per day 24 * 10 if you call every hour) which costs:
![image](https://user-images.githubusercontent.com/5447161/200177440-673d862b-906e-4aa1-90f5-947b51edf715.png)

**Comment by dangalv** [comment]
> @dangalv @thematikma I have updated some code, using my new api3 key I got so far... I'm still recovering from illness, maybe you can try and give some results...
> 
> ```
> 2022-11-06 13:26:40 - altrank - ERROR - Fetching LunarCrush data failed 500 {"error":"Error: You must have at least $1 USD in your LunarCrush payments account to use this endpoint."}
> ```

thank you mate! I hope you feel better, as soon as I can I will try the new config and let you know how it went

**Comment by dangalv** [comment]
@cyberjunky 

Well, I tell you about my experience with the galaxyscore script, which is the script one I need.
The coins are fetched but even if I put a high rank of 150 of the altrank coins and from 40 of galaxyscore, neither activates the bot.
Each API call spends an exuberant amount of credits about 10 credits, and I'm naive thinking that I was going to have 2000 calls. I mean, with one dollar you only get 20 calls to the bot. A scam by lunarcrush.
But removing that detail, the script no longer has any error but does not place any coin on the bot

![image](https://user-images.githubusercontent.com/97088068/200227446-5158f379-cfd0-4b5f-8f51-772169849094.png)

**Comment by thematikma** [comment]
I agree with that. I would wish for a more attractive plan for private users. ~ $350 a year for hourly calls is nuts imho. I guess one could stop the scripts, when the market is low and safe some usd.

**Comment by Gh61** [comment]
I'm honestly thinking about writing some grabber from webui in the future. If it would be possible, you would only need to have Lv. 4. which is one-time payment I suppose.

**Comment by cyberjunky** [comment]
@dangalv the 10 credits was what I expected it would cost for each call (after looking at the pricing), if you could buy 20K credits and call once every hour it would not be so bad...  but the 1$ per day annoys me
That it would gonna cost a lot of money was expected for months... and I think altrank/galaxyscore is not that good anymore anyway...
If you still want me to debug the issue with the ranks please include the debug output. 

@gh61 if the developer api doc tool returns live data we just can scrape that ;-) no levels needed, but I can't check.

**Comment by spggooss** [comment]
> I'm honestly thinking about writing some grabber from webui in the future. If it would be possible, you would only need to have

It is possible already for free with the developer documentation ([https://lunarcrush.com/developers/api/coins](https://lunarcrush.com/developers/api/coins)) . It provides a sample request, but it return the true data. So you dont need to have any Level access to get the data. However, the website is a bit difficult to scrape with no clear html id's etc.

**Comment by Gh61** [comment]
I was able to extract the api token used for testing api request on DEV API DOC.
When I used it in the script api requests to LC are now working.

I don't know, if everyone got the same token, or is it my personal.
So check yours:

![image](https://user-images.githubusercontent.com/10837736/200311806-3c1f5e89-a92c-4980-9156-98054731a934.png)

**Comment by cyberjunky** [comment]
@dangalv I fixed he sorting issue in latest code for altrank, only tested with seperate call, since api.3commas.io is down for me..

**Comment by dangalv** [comment]
> @dangalv I fixed the sorting issue in latest code for altrank, only tested with seperate call, since api.3commas.io is down for me..

Yes, the 3commas api is currently down

![image](https://user-images.githubusercontent.com/97088068/200344353-a588f336-0437-418d-a885-29acb1b8065e.png)

Then when it is enabled I will keep trying to see what happens

**Comment by dangalv** [comment]
altrank working
no same luck with galaxyscore

**Comment by dangalv** [comment]
Great detail of turning off the bot when the credits or day are over :)

**Comment by cyberjunky** [comment]
> altrank working no same luck with galaxyscore

I fixed the galaxyscore issue.
Look like a bug in the LunarCrush API, whenever you sent desc=0 or desc=1 as parameter (which are allowed) the API give false responses.
