### ISSUE TITLE
Error when restarting compound.py after the newest commit

### ISSUE THREAD

**Issue by toonvdijck** [cyberjunky/3commas-cyber-bots#17]
Traceback (most recent call last):
  File "compound.py", line 527, in <module>
    compound_bot(botdata)
  File "compound.py", line 363, in compound_bot
    deals_count, profit_sum = process_deals(deals)
  File "compound.py", line 340, in process_deals
    db.execute(f"INSERT INTO deals (dealid, profit) VALUES ({deal_id}, {profit})")
sqlite3.OperationalError: table deals has no column named profit

**Comment by toonvdijck** [comment]
A workaround is to manually add the column profit in the sqlite3 db.

**Comment by cyberjunky** [comment]
Will fix tomorrow.. thanks for reporting!

**Comment by cyberjunky** [comment]
Created a fix, not tested yet.

**Comment by cyberjunky** [comment]
Closed, I guess it works, can open new if needed.
