### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by MKGort** [cyberjunky/3commas-cyber-bots#18]
Hello.
I have tried installing for use on Ubuntu and PythonAnywhere, following the directions provided.  In both instances, I get the following for either Galaxy or Altrank:

Traceback (most recent call last):
  File "/home/mkgort/3commas-cyber-bots/./galaxyscore.py", line 636, in <module>
    botids = json.loads(config.get("settings", "botids"))
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

The log shows:
10 2021-11-22 21:53:07 - galaxyscore.py - INFO - 3Commas bot helper galaxyscore 
11 2021-11-22 21:53:07 - galaxyscore.py - INFO - Started at Monday 21:53:07 22-11-2021 
12 2021-11-22 21:53:07 - galaxyscore.py - INFO - Loaded configuration from '/home/mkgort/3commas-cyber-bots/galaxyscore.ini'
 13 2021-11-22 21:53:07 - galaxyscore.py - INFO - Using PAPER TRADING account 
14 2021-11-22 21:53:07 - galaxyscore.py - INFO - Notifications are disabled 
15 2021-11-22 21:53:07 - galaxyscore.py - INFO - Reloaded configuration from '/home/mkgort/3commas-cyber-bots/galaxyscore.ini'

And then nothing happens. 

Admittedly I'm not familiar with Python, but I would really like to get this to work.

Do you have any suggestions on what could be the issue?

Cheers!

**Comment by cyberjunky** [comment]
I suspect the config entry for botids is invalid, can you show that?

**Comment by MKGort** [comment]
1 [settings]
  2 timezone = Europe/Amsterdam
  3 timeinterval = 30
  4 debug = True
  5 logrotate = 7
  6 botids = [ lunartest1 ]                                                                                                                                                                     
  7 numberofpairs = 0
  8 maxaltrankscore = 1500
  9 accountmode = paper
 10 3c-apikey = xxxxxx
 11 3c-apisecret = xxxxxx
 12 lc-apikey = 
 13 notifications = False
 14 notify-urls = ['notify-url1']:wq

I have confirmed the name of the bot is exactly "lunartest1"

Thank you for the help!
-MK

**Comment by cyberjunky** [comment]
@MKGort the botid should be the id (number) of the bot, I don't support names (because they can be very long with spaces etc)

So botids = [ 123456 ] 

Where 123456 is the number in the url when you view or edit the bot in 3commas.

**Comment by MKGort** [comment]
Yep, I was using the name instead of the bot id.   I cannot believe I didn't catch that sooner.  Thanks again for the great work.
