### ISSUE TITLE
Blacklist for Stablecoins

### ISSUE THREAD

**Issue by pikespeak** [cyberjunky/3commas-cyber-bots#19]
I use the bot since Sunday and it works well.
I have selected Altlist as data source
Yesterday I loaded the pair USDC/BUSD into the bot and started a trade. Of course, there is not much to expect. 
Would it be possible to make an extra blacklist for stablecoins and then include it in the config file with stablecoin = true/false? Alternatively, each user must always know all stablecoins and include them.
Maybe you can get the list of stablecoins via API from a service like Coinmarketcap?

**Comment by cyberjunky** [comment]
You can blacklist those and other coin pairs in 3Commas and in blacklist.txt already.

**Comment by UrmaGurd** [comment]
You could filter out the LunarCrush data categories that contain "stablecoin".
