### ISSUE TITLE
Enhancement Request - Black List

### ISSUE THREAD

**Issue by MrB-Oo** [cyberjunky/3commas-cyber-bots#2]
Is there are way to overwrite your 3C Black List with a csv list of values?

**Comment by MrB-Oo** [comment]
Yes I think that would be very helpful. That way you can control and update your black list without needing to go onto the 3C interface￼.

**Comment by cyberjunky** [comment]
@MrB-Oo I added the -b option for the local blacklist, just one pair per line

https://github.com/cyberjunky/3commas-cyber-bots/blob/main/README.md#running-the-bot-helpers
