### ISSUE TITLE
Make exchange name configurable in watchlist.ini

### ISSUE THREAD

**Issue by GoempieK** [cyberjunky/3commas-cyber-bots#21]
**Is your feature request related to a problem? Please describe.**
I have multiple Binance accounts in my 3commas account. To keep these apart I renamed them in 3commas.

This prevents the Watchlist.py from working.

**Describe the solution you'd like**
Make the name configurable in watchlist.ini

**Describe alternatives you've considered**
I have renamed one of my account Binance

**Additional context**
I think the reference is given here to the name but my python knowledge is not enough to make a reference to the configuration script here myself.

`    # Get market of 3Commas because it's slightly different then exchanges
    if "Binance" in exchange or "Paper Account" in exchange:
        tickerlist = get_threecommas_market("binance")
    elif exchange == "FTX":
        tickerlist = get_threecommas_market("ftx")
    else:
        logger.error(
            "Bot is using the '%s' exchange which is not implemented yet!" % exchange
        )
        return`

**Comment by cyberjunky** [comment]
Did you leave 'Binance' in the name of your exchanges?
It looks for 'Binance' in exhange string not equal exchange string.

So 'Binance 123', 'Binance 456' etc should still work...

It is currently case sensitive, I will fix this, if the above is true show me one of the exchange names which doesn't work.

**Comment by GoempieK** [comment]
One is called Porsche 911 :-) 
gotta keep your eyes on the prize

I wil test with Binance Porsche 911

**Comment by cyberjunky** [comment]
Haha LOL...

**Comment by cyberjunky** [comment]
I presume it worked, so closing, if you still have an issue please reopen.
