### ISSUE TITLE
Option to stop bots

### ISSUE THREAD

**Issue by tumblewader** [cyberjunky/3commas-cyber-bots#23]
**Is your feature request related to a problem? Please describe.**
There are times when the bot might not be able to update the 3commas bot through an API request,e.g., number of pairs less then number of deals. Not being able to get altrank scores etc. In these cases 3commas will lag behind the altrank scores causing issues. 

The second stop bot feature with an optional close deals features should be tied with bitcoin dump e.g., if bitcoin falls 0.5% in last 15 minutes stop bot and close all open deals. When a dump like that is in effect, lunarcrush stats become useless for an hour or so. So manual intervention is usually required. This could also be tied with overall crypto marketcap, i.e., if crypto market falls by x% in x minutes.  I would love to hear other peoples thoughts on this.

**Describe the solution you'd like**
Option to Stop bot on failure to update the 3commas bot(any error) and on bitcoin dump.

**Comment by rtdevx** [comment]
Maybe Start / Stop selected bots based on certain Fear and Greed Index?

They do provide API:

https://alternative.me/crypto/fear-and-greed-index/

?

**Comment by hunght** [comment]
I try to do the some this what is different between `https://github.com/Zaczero/CBBI` and https://alternative.me/crypto/fear-and-greed-index/ ? which one should I trust?

**Comment by bonjo75** [comment]
Start/Stop bot script is really interesting and IMHO is the most important feature not yet implemented. CBBI indicator is quite to complex to implement, while fear and greed index is easier. Maybe a possible combination of FG index and also drop of BTC price superior to X% will work. Just thoughts...

**Comment by bonjo75** [comment]
by the way in my opinion an efficient way to stop the bot become only by a signal. I would not rely on CBBI indicator or similar

**Comment by cyberjunky** [comment]
Stale ticket, issue fixed, closing, please (re)open if needed.
