### ISSUE TITLE
Feature request - Notification enhancement 

### ISSUE THREAD

**Issue by MrB-Oo** [cyberjunky/3commas-cyber-bots#24]
Feature Request (low priority / nice to have) 

Im having a hard time tracking if all my scripts successfully ran or not and if their are any errors. 

____Solution I would like____

One Telegram bot one to provide summary information 
10:00 - 5 of 5 python scripts on the 1h schedule ran with 0 errors, 0 warnings 
10:15 - 2 of 2 python scripts on the 15m schedule ran with 0 errors, 0 warnings 
10:30 - 1 of 1 python scripts on the 60s schedule ran with 1 errors, 0 warnings* 
10:30 - 5  bots had deals and were compounded

Then a separate telegram bot just for exception notifications  
11:00 - GalaxyScore.py is not running. 
15:00 - Lunacrush api is not responding.
 
*Warning could be bot id not found in 3C

**Comment by cyberjunky** [comment]
I was looking the ability to see if I could embed emoij in the messages, but can see how apprise supports this.
Also have some code in where I bundle all messages from a single run in one message, this cleans up the telegram channel a lot.
Not sure how to tackle the reporting part though, it doesn't look that easy at first side.

**Comment by MrB-Oo** [comment]
Thanks for the consideration.
