### ISSUE TITLE
getting error when tried to add Kucoin bot -Bot is using the 'kucoin' exchange which is not implemented yet!

### ISSUE THREAD

**Issue by mshaltaf** [cyberjunky/3commas-cyber-bots#29]
**Describe the bug**
i have tried to add Kucoin bot and connect it with bot helper altrank but i'm getting the below error 
"Bot is using the 'kucoin123' exchange which is not implemented yet!"

**Comment by cyberjunky** [comment]
@mshaltaf Thank you for reporting!
This error message if from an older version of altrank, it should be supported (but KuCoin was not tested by me) in the latest version.
So please update en let me know.

**Comment by mshaltaf** [comment]
Hello @cyberjunky thanks for your reply i have tried with the new version and now getting diffrent errror , even though i tested with binince bot ... below the error 

Traceback (most recent call last):
  File "./altrank.py", line 648, in <module>
    find_pairs(botdata)
  File "./altrank.py", line 430, in find_pairs
    marketcode = get_threecommas_account(thebot["account_id"])
  File "./altrank.py", line 302, in get_threecommas_account
    for account in data:
TypeError: 'NoneType' object is not iterable

**Comment by cyberjunky** [comment]
We are getting there... you need to add AccountRead permissions to newly created 3Commas APIKeys... and use those.

**Comment by mshaltaf** [comment]
@cyberjunky , thank you , yes i have checked this and now it is working great ..

**Comment by cyberjunky** [comment]
Great, I close this, you can open a new issue if you encounter a bug or have a idea..
