### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by MrB-Oo** [cyberjunky/3commas-cyber-bots#3]
Hi CyberJunky, 
Is it possible to include a log purge after x amount of runs ?

**Comment by cyberjunky** [comment]
@MrB-Oo I have added logrotate to altrank, galaxyscore and watchlist, compound will follow.
Default = keep 7 days, but you can tweak the settings.

**Comment by MrB-Oo** [comment]
Thanks for including this.
