### ISSUE TITLE
TP Increment account type fix

### ISSUE THREAD

**Issue by adzw01** [cyberjunky/3commas-cyber-bots#31]
Hi mate

please see attached fixes. there was an issue with checking for deals depending on what account was selected within the 3commas website (paper / real).

i have fixed this and also removed code which is no longer needed.

thanks
[tpincrement.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/7614075/tpincrement.txt)

**Comment by cyberjunky** [comment]
I merged it, thanks!
