### ISSUE TITLE
TP Increment - further enhancments

### ISSUE THREAD

**Issue by adzw01** [cyberjunky/3commas-cyber-bots#32]
Hi me again

i have been using this with great sucess and increasing the profits more on my account. but i have increased my safety order allocation on my deals which could result in a big TP % increase, so I wanted more control of the increase TP % per completed SO.

So i have implemented a 'step scale', which will increase each safety order to a specifed amount. For example, the config file now needs the following variable:

increment-step-scale = [0.1, 0.05, 0.03]

so how this works using the above config, is:
safety order 1 increment is 0.1%
safety order 2 increment is 0.05%
safety order 3 increment is 0.03%
safety orders > 3 are ignored and not adjusted (you can increase the number of steps in the config to cater more safety orders e.g. [0.1, 0.05, 0.03, 0.03, 0.03] will cater for 5 SO)

upon each update inteval, the safety orders are compared from the last 'run', so no SO are missed, the difference is then calculated.
For example, using the above example config:
update interval 1 = SO's complete is 0, so the increase is 0%
update interval 2 = SO's complete is 2, so the increase is 0.15%
update interval 3 = SO's complete is 3, so the increase is 0.03%

the following lines within the documentation are now invalid following this change, so can be removed:
- If the increment value is changed in the config file, all existing deals will use the original value which is stored in the DB - so the config will not affect older deals.
- Default increments are 0.1% for every SO completed - this can be changed in the config file.

the examples above can be added to the documentation so users can understand the concept.

this can also be ran as a service so might need a template in the scripts folder :)

This should help anyone which has a large value of max safety orders on their deals, or just want to fine tune the TP% increase for each SO.

[tpincrement.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/7618649/tpincrement.txt)

**Comment by cyberjunky** [comment]
@adzw01 Thanks again! It's online, going to edit README now, Added upgrade_config() code, something new useful for future update of other scripts too.
