### ISSUE TITLE
blacklist.txt being semi ignored?

### ISSUE THREAD

**Issue by adzw01** [cyberjunky/3commas-cyber-bots#33]
Hi

i dont think the local blacklist is working correctly.

my blacklist.txt reads this:
USDT_SHIB
USDT_BTC
USDT_ETH

but SHIB is still being selected in the pair selection. (i cant use the 3commas blacklist as i have got another bot dedicated to trading SHIB, hence i dont want it included in my altrank bot)

the below log shows its read the 3 pairs from blacklist.txt but the updated pairs is still including USDT_SHIB.

2021-11-29 21:17:59 - altrank.py - Reading local blacklist file 'blacklist.txt' OK (3 pairs)

2021-11-29 21:15:23 - altrank.py - Bot 'Multipair USDT' with id '#######' updated with these pairs:
['USDT_RSR', 'USDT_XTZ', 'USDT_SYS', 'USDT_SHIB', 'USDT_MBOX', 'USDT_MATIC', 'USDT_COTI', 'USDT_ZIL', 'USDT_CAKE', 'USDT_RAY']

**Comment by adzw01** [comment]
ok i found the offending line.

newblacklist = file.readlines()
needs changing to
newblacklist = file.read().splitlines()

readlines() was putting '\n' at the end of each pair when a new line followed.

the blacklist worked fine with one pair only, but multiple lines it was ignoring.

**Comment by cyberjunky** [comment]
Should be solved with patches from @toonvdijck, I patched the watchlist_ code, thanks both!
