### ISSUE TITLE
Compound profit over all running bots

### ISSUE THREAD

**Issue by toonvdijck** [cyberjunky/3commas-cyber-bots#36]
**Is your feature request related to a problem? Please describe.**
It would be nice to group some bots and distribute the total profit.

**Describe the solution you'd like**
Example: You have botids 1001, 1002,1003 and 1004.
Bot 1001 takes 1USD/btc profit. It would compound 0,25 into each bot.

**Describe alternatives you've considered**
/

**Additional context**
It would be even better tot have a distribution key to give some bots more weight for compounding profit.

**Comment by cyberjunky** [comment]
Isn't this too complicated, and negative profit will affect other bots

**Comment by brhahlen** [comment]
I would actually prefer to have this the other way around:
Botids 1001, 1002, 1003 and 1004 are all running.
All the profit combined is distributed into bot 1001.
