### ISSUE TITLE
TSL Helper

### ISSUE THREAD

**Issue by adzw01** [cyberjunky/3commas-cyber-bots#38]
So another feature I've created. The ability to update the SL with a TSL function.

As 3C doesnt appear to allow any TSL for bots, only TTP. TSL only appears to work on smart trade, so I want the ability to have TSL for my futures bots which dont have any SO.

Not sure how this script would work with bots that make use of many SO's - so please bear this in mind.

activation-percentage in the config, will only check and activate the TSL when the profit % is >= . Below the activation-percentage, the SL is not updated.

I would suggest a quicker interval for checking, so the config sets this to 90 seconds by default.

You must have a SL set on the deals within the bot you want this script to manage.

The script will keep track of the last profit % the SL was updated, and will compare the lastest profit %, and move the TSL up when required. The script does not move the SL down, as this wouldnt make sense.
I have also catered for the fact that the user might update the SL manually after activation on the 3C website - in this case the TSL is restarted for the deal that was manually altered.

Appears to work, again this only has limited testing.

I would use this with caution. I am only using this to reduce my liquidation risk on my futures bots - but could be used with spot bots if you know what you're doing.
[tsl.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/7654584/tsl.txt)

**Comment by cyberjunky** [comment]
Thanks! (again)

**Comment by cyberjunky** [comment]
I have updated the README, of you see anything wrong or have something new to add, please let me know.
