### ISSUE TITLE
compound.py gives UnicodeEncodeError

### ISSUE THREAD

**Issue by bramjekel** [cyberjunky/3commas-cyber-bots#39]
Python gives the following error when running compound.py

--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files (x86)\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u20bf' in position 54: character maps to <undefined>
Call stack:
  File "compound.py", line 541, in <module>
    compound_bot(botdata)
  File "compound.py", line 413, in compound_bot
    update_bot(
  File "compound.py", line 300, in update_bot
    logger.info(
  File "compound.py", line 167, in info
    self.log(message, "info")
  File "compound.py", line 157, in log
    self.my_logger.info(message)

**Comment by cyberjunky** [comment]
Hi Bram, how is your Bot called?

**Comment by bramjekel** [comment]
It's called: LunarCrush Auto Top 10 Alt Daily v6 - TP1%/2SO

I love short names ;-)

**Comment by toonvdijck** [comment]
It is related to the Bitcoin symbol.
https://www.charactercodes.net/20BF

**Comment by bramjekel** [comment]
You mean I have to adjust the python code...?

**Comment by toonvdijck** [comment]
That could be a temporary work around :)

**Comment by cyberjunky** [comment]
@bramjekel can you check latest code of compound.py? (no version update, just pick the one from repo)

**Comment by bramjekel** [comment]
unfortunately, i still get the same error message

**Comment by cyberjunky** [comment]
@bramjekel can you paste the name of the bot?

It works for me with t bitcoin symbol, but that already worked without the gix.

Probably due to using the correct encoding on my system (utf8), what environment are you running it on?
If run on linux what does this give:
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=nl_NL.UTF-8
LC_NAME=nl_NL.UTF-8
LC_ADDRESS=nl_NL.UTF-8
LC_TELEPHONE=nl_NL.UTF-8
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION=nl_NL.UTF-8
LC_ALL=

```

**Comment by cyberjunky** [comment]
Ah yeah a win 10 install, I forgot.
Can you give a screenshot of the name, since it doesn't show it contains a bitcoin symbol when pasted.

Can you paste this in a python prompt, or in a file and run it?
```
import locale
all = locale.locale_alias().items()
utfs = [(k,v) for k,v in all if 'utf' in k.lower() or 'utf' in v.lower()]

# utf settings starting with en
en_utfs = [(k,v) for k,v in utfs if k.lower()[:2].lower() == 'en' or 
            v.lower()[:2] == 'en'

print en_utfs
```

**Comment by bramjekel** [comment]
first I got this error: 

  File "encode.py", line 9
    print en_utfs
    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(en_utfs)?

When I changed the last line of code to print (en_utfs) I got this error:

  File "encode.py", line 9
    print(en_utfs)
    ^
SyntaxError: invalid syntax

**Comment by cyberjunky** [comment]
```
import locale
print(locale.getlocale())
```

**Comment by bramjekel** [comment]
('Dutch_Netherlands', '1252')

**Comment by cyberjunky** [comment]
Can you add this near top of compound.py and see if it fixes anything?
```
import locale
locale.setlocale(locale.LC_ALL, "en_US.UTF8")
```

**Comment by bramjekel** [comment]
Unfortunately still the same error :-(

**Comment by bramjekel** [comment]
@cyberjunky I have been searching and tweaking myself and discovered the following.

if i replace this section:

----

```
    def __init__(self, filename="", when="midnight", interval=1, backupCount=7):
        super().__init__(
            filename=filename,
            when=when,
            interval=int(interval),
            backupCount=int(backupCount),
        )
```

----

with this section

----

```
    def __init__(self, filename="", when="midnight", interval=1, backupCount=7, encoding='utf-8'):
        super().__init__(
            filename=filename,
            when=when,
            interval=int(interval),
            backupCount=int(backupCount),
			encoding=encoding
        )
```

----

and add the encoding to this as well, like:

```
        # Log to file and rotate if needed
        file_handle = TimedRotatingFileHandler(
            filename=f"{datadir}/logs/{program}.log", backupCount=logstokeep, encoding='utf-8'
        )
```

then I do not get an error...

**Comment by toonvdijck** [comment]
@bramjekel Is the problem solved with your solution?

I have this error also (win10 install)

**Comment by bramjekel** [comment]
@toonvdijck yes it was

**Comment by cyberjunky** [comment]
I have added it to the code base, thanks!
