### ISSUE TITLE
compound.py throws error for real bots when paper trading is active

### ISSUE THREAD

**Issue by brhahlen** [cyberjunky/3commas-cyber-bots#44]
**Describe the bug**
Running `compound.py` on a real bot, when Paper Trading is active on the 3Commas site will throw an error:
```
2021-12-15 13:21:51 - compound.py - ERROR - Fetching deals failed with error: {}
```

**To Reproduce**
1. Which program you run
`compound.py`
2. Relevant settings used (don't paste your bot-id's, or any api-key values!)
Pretty default settings, TP Increment to 0.75
3. Error you get
`2021-12-15 13:21:51 - compound.py - ERROR - Fetching deals failed with error: {}`
4. Anything else what is important
Paper trading must be active on the 3Commas Website, and the bot that is being compounded must be a real bot.

**Expected behavior**
Normal compounding without errors.

**Environment:**
 - Python version: python3 -V
`Python 3.8.12`
 - Operating System: uname -a
`Linux compound-btc 5.15.7-200.fc35.x86_64 #1 SMP Wed Dec 8 19:00:47 UTC 2021 x86_64 GNU/Linux`
Running in Docker
 - Version of software [e.g. 0.6.1]:
 Current master branch

**Additional context**

**Comment by cyberjunky** [comment]
@brhahlen Can you try latest version of compound.py? (from repo, no version update yet)

**Comment by brhahlen** [comment]
@cyberjunky Will give it a spin tomorrow!

**Comment by brhahlen** [comment]
@cyberjunky That works!

However, I see that you're passing a `Forced-mode: Real` header, which I think means it only works for Real trading?
Now, I don't need to compound on Paper, but there might be people that do, so that might cause issues later on?

Again, for me this is fine!
Thanks!

**Comment by cyberjunky** [comment]
@brhalen some data is only available under real mode, so you need to force it, it's a quirk of 3Comma's, under paper mode it will work too.

**Comment by cyberjunky** [comment]
I will close it.
