### ISSUE TITLE
Leverage

### ISSUE THREAD

**Issue by jak9nn** [cyberjunky/3commas-cyber-bots#45]
Hi, everything works absolutely fantastic, but I have a problem with futures.  Why the minimum leverage is only 25, and the minimum basic order varies by pairs. It could be done to use a maximum leverage of 100x.  And for a pair where it is not allowed leverage 100x the maximum allowed leverage for that pair?  When this error pops up, the pairs no longer update. Thank you ![image](https://user-images.githubusercontent.com/85456287/146357817-8bd03aac-78b1-4f80-881d-6124d399118a.jpeg)

**Comment by cyberjunky** [comment]
I suspect the minimum settings changed because the pairs changed, and 3C is no longer accepting the bot settings it had with the old pairs/ No sure how to fix it. I could check the error and change parameters accordingly, but that doesn't sound very safe thing to do without knowledge of user.

**Comment by jak9nn** [comment]
Now I have to put every pair that has a bigger base order than $10 to blacklist on 3commas. It's tedious and one day $10 may be enough, but the other day when the price of the crypto flies up so the minimum order is for example $11 and it already writes me an error, and gave no longer updated pairs. Then I have to add another pair to the blacklist.

**Comment by cyberjunky** [comment]
Sorry I don't know how to fix this, it's too dynamic and information is missing in the API to code around it.
I can find minimum trading values for pairs, but not minimum leverage information and acting upon an error message is too tricky, you don't leverage settings to be changed automatically. Closing for now,
