### ISSUE TITLE
compound.py not finding bot ID's

### ISSUE THREAD

**Issue by cbkn76** [cyberjunky/3commas-cyber-bots#47]
Hello, I'm on a raspberry pi with Bullseye. I'm not sure if this is a bug or most likely something I'm doing wrong. when I run python3 ./compound.py each bot ID i setup in the .ini comes back as not found. 

Error Occurred compounding bots: other error occurred: not_found Not Found None

This happens for each bot id, I have triple checked each bot id # is correct. i have also put in my 3commas api and key.

Also, when i try to run the command to view the error log errors come up saying path could not be found, I noticed in the errors it shows path /home/ron... even though i had edited the compound files in /scripts to reflect the correct username and path.
any quick things to check?

**Comment by cyberjunky** [comment]
What syntax does you botids  settings line use?
Did you install the files from the scripts directory, just editing is not enough

**Comment by cbkn76** [comment]
First, I want to thank you for these bot helpers. they are incredible and I hope I am able to get them working.
 I put the numerical ID of the bots [12345678, 87654321]
what is the command to install the .service files from the scripts folder?

**Comment by cbkn76** [comment]
Ok, i re-read the directions and yes I had ran the systemctl commands for the 3commas-compound-bot.service . I ran them again and verified no errors. Attaching an image of the status check
![Uploading 453D7EDA-0569-4300-926F-26D05CBF4C07.jpeg…]()

**Comment by cbkn76** [comment]
![Uploading D728B25D-2A18-4822-B217-7BE89199C5AE.jpeg…]()

**Comment by cyberjunky** [comment]
Edit the paths inside the files you need then install as described here:
https://github.com/cyberjunky/3commas-cyber-bots#start-automatically

**Comment by cbkn76** [comment]
I had updated the paths already, but i think i found my problem. looks like i was using the deal ID, it changes with every deal. where do i find the bot id?? is it a number, or the name of the bot??

**Comment by cbkn76** [comment]
You can mark as closed, i reinstalled on a fresh version of raspbian and it works fine. thank you for the help and a hundred thanks for these great bots!!
