### ISSUE TITLE
trailingstoploss enhancments

### ISSUE THREAD

**Issue by adzw01** [cyberjunky/3commas-cyber-bots#50]
updated the code to add a initial set % which is specified in the config file.

this will allow the below scenario:
original deal SL is 5%
the activation % is triggered at 2% profit
the script can move the SL straight to -0.01% to guarantee profit
the TSL will then track the price up to ensure more guaranteed profit.

users need to amend the following in the ini file (upgrade code included in script):
set-sl-percentage-at-first-activation.
value '[]' = empty -  which means the script will continue working as the old revision and a traditional TSL
a decimal value = a specified amount the SL will immediately be set to on the first activation

[trailingstoploss.txt](https://github.com/cyberjunky/3commas-cyber-bots/files/7757365/trailingstoploss.txt)

**Comment by cyberjunky** [comment]
@adzw01 agreed if I call the config setting 'initial-stoploss-percentage' ?
Without understanding all code yet, so could be wrong naming...

**Comment by cyberjunky** [comment]
This round code block seems wrong with if then inside? Or is python knowledge failing ;-)
```
 new_stoploss = round(
						set_sl_value_at_first_activation
						if existing_deal is None
						and set_sl_value_at_first_activation is not None #if the deal has never been tracked before and an inital SL value has been set in the config
                        else stoploss + (last_profit_percentage - actual_profit_percentage),
                        2,
                    )
```

**Comment by adzw01** [comment]
python knowledge failing ;) its correct. ive got 4 people using it, with the optional initial % and some without as a pure TSL :)
feel free to rename the variable though if you wish

**Comment by cyberjunky** [comment]
I have committed the code (held 0 as default for disabled initial-stoploss-percentage, but not sure if this is working correct)
Please test after Christmas ;-)

**Comment by adzw01** [comment]
it might be better to leave the initial % as [] (empty), so it works as a traditional SL with the optional ability to set the value so the SL is pushed to the set % on the first activiation?

merry christmas my friend

**Comment by cyberjunky** [comment]
[] doesn't look like empty entry,  more an empty array, can be confusing?
Will give it another though.. thanks! Greetings!

**Comment by adzw01** [comment]
its the only way i could get the ini file to accept an empty value, as leaving it as blank would throw an error. the only issue with setting it as 0, means the SL will be moved to 0% at the first activation, and this might not be what everyone wants :) if that makes sense

**Comment by cyberjunky** [comment]
I changed it to your code, indeed not easy to fix without extra code/overhead. Thanks!
