### ISSUE TITLE
FTX perpetuals not recognized 

### ISSUE THREAD

**Issue by Akomans** [cyberjunky/3commas-cyber-bots#51]
Perpetual coins are not being recognized by the tool i wonder if its possible to include them. Thank you for your hard work !!

**Comment by Akomans** [comment]
![image](https://user-images.githubusercontent.com/83137098/147191467-52ba2359-4acb-401f-bd05-1722cabedc68.png)

**Comment by cyberjunky** [comment]
@akomans I'm not using FTX but aren't they using using xxxPERP kinda of name scheme?
Can you give some examples, to see if this can be implemented, it doesn't look like it..

**Comment by Akomans** [comment]
oh it worked already when i added +"-PERP".   thank you

**Comment by cyberjunky** [comment]
@Akomans can you point out where? Curious...

**Comment by cyberjunky** [comment]
@Akomans Ping.

**Comment by Akomans** [comment]
sorry about the late reply i added +"-PERP" at the end of specific line but lose my edited file so cant remember maybe you can find it ? if you could include ftx perpetuals that would be perfect

**Comment by cyberjunky** [comment]
Thanks, I implemented it in latest version, close this for now, if you can test would be nice...
