### ISSUE TITLE
Keep getting Not a crypto trigger message, or exchange not yet supported.

### ISSUE THREAD

**Issue by Timozack88** [cyberjunky/3commas-cyber-bots#52]
Dear , 

I get error with watchlist.py Not a crypto trigger message, or exchange not yet supported. while testing the helper 

i have tried all type of message to trigger the bot but i keep getting this error 
![Screenshot_4](https://user-images.githubusercontent.com/96510605/147318211-7682a9e4-be66-42b3-9cf2-44a9e8fee194.png)

kindly let me know how do I trigger the bot with message also how can we change the trigger message to ( Buy #coin , #coin buy )

Thanks for the amazing scripts .

**Comment by cyberjunky** [comment]
Hi, the format is wrong, the code is written for the ['wiseanalize' ](https://t.me/wiseanalize) telegram channel.
You can join it to see how it looks.
