### ISSUE TITLE
Blacklist for futures dont work

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#58]
Hello! first thanks for your work!
Now I have to clarify that I have very basic knowledge but something I defend myself. Oh and I hope the translator is understood.
The bot works correctly, except for the blacklist in futures.
To confirm that I start a new clean task: I delete the previous galaxyscore.ini then I set the blacklist.txt,. And I run the galaxyscore.py again.
For example there is a pair in binance futures that was running continuously USDT_NEARUSDT and I had already put it in the blacklist.txt. Unfortunately the native 3commas blacklist does not omit these pairs and the bot places them the same, as my SO and BO is the minimum, the bot does not save the changes and does nothing showing me an insufficient funds error from the 3c-helper, since NEAR It asks for 17 dollars minimum to run.
I really don't know how to make the bot skip certain pairs from 3c cyber-bots helper
I hope you give me a hand, thank you!

![image](https://user-images.githubusercontent.com/97088068/148031155-5ab5b13b-8629-4aed-86c7-bdc4a36dc29a.png)

**Comment by toonvdijck** [comment]
#57 Should fix this i suppose.

**Comment by dangalv** [comment]
> #57 Should fix this i suppose.

Thanks! I'll check it

**Comment by cyberjunky** [comment]
@dangalv what does your -d and or -b parameter look like?

**Comment by dangalv** [comment]
> @dangalv what does your -d and or -b parameter look like?
Sorry friend, I'm half green in terms of certain technicalities in this language, should I run that parameter in the console? How should i do it? thanks

**Comment by cyberjunky** [comment]
@dangalv you want to use a blacklist, you have enabled it using the -b argument you give when executing the script.
So in short, with which command and arguments do you start the script above? ;-)

**Comment by dangalv** [comment]
> @dangalv quiere usar una lista negra, la ha habilitado usando el argumento -b que da al ejecutar el script. Entonces, en resumen, ¿con qué comando y argumentos inicias el script anterior? ;-)

I was run it directly without any argument, I was open the .py file and put the program to run from the compiler..
Now I run it from the console in the "main" part but it tells me that the -b parameter expects an argument. I have tried in different ways because I don't have a clear understanding of python apart from the logic of certain things in the program.

![arg](https://user-images.githubusercontent.com/97088068/148250651-f8298464-b240-4392-acab-eeb893bd2183.png)

**Comment by cyberjunky** [comment]
Yeah you have to run it as described... closing

**Comment by dangalv** [comment]
asdasd

> Yeah you have to run it as described... closing

I ran the file with the mentioned parameters and the wizard keeps putting the blacklisted pairs 😥

![image](https://user-images.githubusercontent.com/97088068/148268367-004d8fe6-b0a2-4067-81c8-ae7e3116c459.png)

![image](https://user-images.githubusercontent.com/97088068/148268479-6aded55f-633f-49ea-b221-04d82f38be12.png)

**Comment by cyberjunky** [comment]
Please read!!!!!!

It says it can't open the blacklist, thats whi I asked you to specify how you start it.
The blacklist is called blacklist.txt so you need to add -b blacklist.txt...

**Comment by dangalv** [comment]
> Please read!!!!!!
> 
> It says it can't open the blacklist, thats whi I asked you to specify how you start it. The blacklist is called blacklist.txt so you need to add -b blacklist.txt...

ok it's true some time ago I put the extension txt and I had been told that the file was not found so I discarded putting the extension.
Now the wizard read the blacklist but the skipped pairs are still being placed

![image](https://user-images.githubusercontent.com/97088068/148271587-dcd74f6f-4465-4eb4-b380-2dca51d41f4b.png)

![image](https://user-images.githubusercontent.com/97088068/148272355-974395b5-2ac2-433f-b42e-1b092ac77beb.png)

**Comment by dangalv** [comment]
...
Someone else to help me with this problem that the wizard does not read the futures blacklist?

**Comment by cyberjunky** [comment]
Did you try with -b blacklist.txt yet?
First you must get rid of the error opening the blacklist.

**Comment by dangalv** [comment]
> Did you try with -b blacklist.txt yet? First you must get rid of the error opening the blacklist.

Yes, as I said in the previous message it was able to read the blacklist, but the wizard seems to only execute the common pairs for example BTC_USDT but it does not execute the USDT_BTCUSDT futures pairs.
Tested on paper wallet (works) and then on real futures account (doesn't work)

**Comment by cyberjunky** [comment]
Your base_order and safety_order values are too low, I cannot fix that since minimum base order value changes per pair, and even over time for same pair, this script only changes pairs not the other values, you need to change the bot settings I guess. So when the script changes the pairs, there can be another minimum value needed and the script just use the values from the bot which were in there already

**Comment by dangalv** [comment]
> Your base_order and safety_order values are too low, I cannot fix that since minimum base order value changes per pair, and even over time for same pair, this script only changes pairs not the other values, you need to change the bot settings I guess. So when the script changes the pairs, there can be another minimum value needed and the script just use the values from the bot which were in there already

It's precisely for that problem (base_order / safety_order values are too low) that I want to use the blacklist to be able to omit those pairs that need a high capital such as SOL, UNI, BTC, etc.

**Comment by cyberjunky** [comment]
I understand, so USDT_UNIUSDT is on a line in the blacklist.txt right?
Can you set debug = True in your altrank.ini file and run again until error comes up, then copy last part of the logs/altrank.log showing what it does?
You can mask the botid's and other info you want to hide.

**Comment by dangalv** [comment]
> I understand, so USDT_UNIUSDT is on a line in the blacklist.txt right? Can you set debug = True in your altrank.ini file and run again until error comes up, then copy last part of the logs/altrank.log showing what it does? You can mask the botid's and other info you want to hide.
[altrank.log](https://github.com/cyberjunky/3commas-cyber-bots/files/7824142/altrank.log)

**Comment by dangalv** [comment]
It seems that now it works, you just have to put the pair in the traditional way: "btc_usdt" instead of "usdt_btcusdt".

**Comment by cyberjunky** [comment]
Since you remove the log I can't check why and fix it, or document it, but nice to hear it works.

**Comment by dangalv** [comment]
> Since you remove the log I can't check why and fix it, or document it, but nice to hear it works.

Ready! It seemed impossible but the correct syntax for futures is for example:
USDT_BTC
USDT_SOL
USDT_UNI

In this way, checked by me and with several pairs, there is no problem with the blacklist and futures.

thanks
