### ISSUE TITLE
I cannot link the telegram account with the bot helper

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#59]
Hello again! you don't know how much I tried to avoid having to ask for help but I don't know what else to do :/

I comment the case I followed all the steps to get my bot token and chat id, then I embed it in the main code. As shown in the tutorial example.
And it cannot be started.
![telegram error2](https://user-images.githubusercontent.com/97088068/148635488-9ab741e0-3110-4c20-8077-9f306acc6dd8.png)

"
Traceback (most recent call last):
  File "/home/droidg/3commas-cyber-bots/altrank.py", line 185, in <module>
    notification = NotificationHandler(
  File "/home/droidg/3commas-cyber-bots/./helpers/logging.py", line 22, in __init__
    urls = json.loads(notify_urls)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
"

I installed Apprise to auto-send me a message and it arrived correctly, so the chat id and the bot id works fine

![Captura de pantalla 2022-01-08 042159](https://user-images.githubusercontent.com/97088068/148635733-ac2f4664-f40a-4bb4-aaf7-5e3053fa659e.png)

![Captura de pantalla 2022-01-08 042311](https://user-images.githubusercontent.com/97088068/148635744-779a0ea8-6c39-4b33-a034-2e8aaeea02f5.png)

It's the last thing I need to learn. I hope you can give me a hand. Thank you

**Comment by cyberjunky** [comment]
@dangalv It looks like an syntax error in notify_url setting, something with more than one " or , please look closely

**Comment by dangalv** [comment]
> @dangalv It looks like an syntax error in notify_url setting, something with more than one " or , please look closely

this part (bold letter) I copied from your example code, is okay?:
notify-urls = ["tgram://{bot_token}/%%{chat_id}/**_?image=False&detect=yes&format=text&overflow=upstream&rto=4.0&cto=4.0&verify=yes"_**

I put the code without that extra code part and the error is the same.

ex:
notify-urls = ["tgram://{bot_token}/&&{chat_id}/"]

**Comment by cyberjunky** [comment]
You need to fill the altrank.ini file, NOT using the format like you posted above ```cfg["settings']..```

Using this format like described in the readme, no commas or json formatting:
```
[settings]
timezone = Europe/Amsterdam
timeinterval = 1800
debug = False
logrotate = 14
botids = [ 123456 ]
numberofpairs = 10
maxaltrankscore = 250
3c-apikey = 4mzhnpio6la4h1158ylt2
3c-apisecret = 4mzhnpio6la4h1158ylt4mzhnpio6la4h1158ylt4mzhnpio6la4h1158ylt4mzhnpio6la4h1158ylt4mzhnpio6la4h1158ylt4mzhnpio6la4h1158ylt4mzhnpio6la4h1158ylt4mzhnpio6la4h1158ylt
lc-apikey = z2cwr88jkyclno8ryj0f
notifications = True
notify-urls = [ "tgram://9995888120:BoJPor6opeHyxx5VVZPX-BoJPor6opeHyxx5VVZPX/" ]
```

**Comment by dangalv** [comment]
> 

Oh great! It worked modifying it from the "ini" file and not the ".py" file as I did 

lot of thanks! 

// off:
I don't know if I have to open another topic regarding a trouble about the amount of coins it bot helper scans (only 100). But this problem is not a high priority, anyway it caught my attention that the helper analyzed (fetched) only 100 currencies in the ranking and I from the cfg file "maxaltrankscore" put a value greater than 100 (exactly 1500 "default")
//

**Comment by cyberjunky** [comment]
Nice you got it working.
For now the 100 limit is hardcoded yes, but planned to make it configurable, even fetching 1000 coins is not a problem, but wanted to keep it lightweight.
The high value of maxaltrankscore is set so high to be sure it's disabled by default. It's used by galaxyscore only.

**Comment by dangalv** [comment]
> Nice you got it working.
> For now the 100 limit is hardcoded yes, but planned to make it configurable, even fetching 1000 coins is not a problem, but wanted to keep it lightweight.
> The high value of maxaltrankscore is set so high to be sure it's disabled by default. It's used by galaxyscore only.

Thank you sir, I hope you can make it possible! I will gratefully support your tool as soon as I can see that it is working for me as expected, this deserves recognition from the community.

**Comment by cyberjunky** [comment]
I have made the lunarcrush fetchlimit configurable in latest code.
Just run altrank again after update and value is added to your ini file.
Make sure it's set slightly higher than the pairs you need, since some can be blacklisted or don't reach minimal 24h volume

**Comment by dangalv** [comment]
> I have made the lunarcrush fetchlimit configurable in latest code. Just run altrank again after update and value is added to your ini file. Make sure it's set slightly higher than the pairs you need, since some can be blacklisted or don't reach minimal 24h volume

Wow how fast! I'll take a look at it as soon as I can. Thanks!
