### ISSUE TITLE
lunarcrush api stopped working?

### ISSUE THREAD

**Issue by dangalv** [cyberjunky/3commas-cyber-bots#62]
Hi all! Could you confirm if the lunarcrush api stopped working?
I used a free one which was this: "https://api.lunarcrush.com/v2" and now it tells me this in the error reports: "Fetching LunarCrush data failed with error: 401 Client Error: Unauthorized for url: https://api.lunarcrush.com /v2?data=market&type=fast&sort=acr&limit=1500&key=https%3A%2F%2Fapi.lunarcrush.com%2Fv2 "

**Comment by hunght** [comment]
I think so, This is the message from the site:
```
API
A new LunarCrush API is coming soon!
The new API will be available in the 2nd quarter of 2022.

You will need to be holding a certain amount of $Lunr Token in order to gain access, which will be a new level on LunarCrush, and based on usage, $Lunr Token will need to be deposited to maintain a specific balance and level.
```

**Comment by dangalv** [comment]
> I think so, This is the message from the site:

Yes I just read it! I can not believe it

**Comment by dangalv** [comment]
You can't use the LunarCrush announcement telegram to update the list of altcoins? Although there are only 10 altcoins at least to wait for the new api.

![image](https://user-images.githubusercontent.com/97088068/149051826-281df5ea-8abc-4d81-a03c-c4986c18bb81.png)

**Comment by thematikma** [comment]
I did generate a API Key under settings on legacy.lunarcrush.com. After putting the key in the respective ini files and restart the scripts, everything is working again. For now.
