### ISSUE TITLE
Notifications for tsl_and_tp.py

### ISSUE THREAD

**Issue by DeFiFarmerJohn** [cyberjunky/3commas-cyber-bots#70]
**Is your feature request related to a problem? Please describe.**
When using the  tsl_and_tp.py, a notification is sent every 120 seconds. The same as when it runs.  I want the notifications when a change is made, but not every 2 minutes when there is no change.
**Describe the solution you'd like**
Add a line of code that allows notifications only when the py makes a change to the current deal.
**Describe alternatives you've considered**

**Additional context**
I really love the work you have done!
Thank you.

**Comment by amargedon** [comment]
This tsl_and_tp script is a first version created by me, currently I'm working on an improved version in another developer branch. Over there the amount of notifications has been tuned down to exactly what you expect; only a notification when a deal has been updated.

I expect this new version somewhere towards the end of this week, or next week, to become available in the main repository of Cyberjunky!

Alternatively, if that takes too long, you could check out my development branch over here: https://github.com/amargedon/3commas-cyber-bots/tree/tsl_and_tp. The scripts has been renamed from tsl_and_tp.py to trailingstoploss_tp.py and now also includes an option to increase the TP as well. Everything explained in the Readme.

**Comment by DeFiFarmerJohn** [comment]
Thank you Sir.  I appreciate the feedback

**Comment by cyberjunky** [comment]
This code is currently present in the repository under name 'trailingstoploss_tp.py', so closing this.

**Comment by DeFiFarmerJohn** [comment]
Thank you
