### ISSUE TITLE
Watchlist - another format

### ISSUE THREAD

**Issue by spammik** [cyberjunky/3commas-cyber-bots#75]
Hi, would it be possible to set the watchlist to a different telegram message format? 
For example, I receive messages in the format: 

**WIN/USDT**
Vol: 8965790.70 Base: 0.00566600 Price: 0.00508700

Thanks in advance.

**Comment by cyberjunky** [comment]
Hi Spammik, this is not easy currently, thinking about some sort of template with placeholders, but there are many different formats

**Comment by cyberjunky** [comment]
@spammik which telegram channel is this? I can have a look if format is strict

**Comment by cyberjunky** [comment]
Stale ticket, closing, please (re)open if needed.
