### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by MrB-Oo** [cyberjunky/3commas-cyber-bots#8]
Hi Cyberjunky, Kindly can you implement a time zone setting (TZ) in the *ini files ?

import os
import time
os.environ["TZ"] = "xxx/xxxx"
time.tzset()

**Comment by cyberjunky** [comment]
Hi, can you show me what is wrong? The logging date/format and or something else?
Maybe I can find it in a more elegant way..

**Comment by MrB-Oo** [comment]
Im running the scripts on pythonanywhere.com, the timezone on there servers are different to me. So when telegram sends me a notification i.e ....Next update in 3600 Seconds at hh:mm:ss is 60min in the past for me.

**Comment by cyberjunky** [comment]
@MrB-Oo I added a timezone setting in version 0.7.2 can you test it?
Your code snippet seem to work in the end.

**Comment by cyberjunky** [comment]
I will close this one, since it should solve your issue, except not on Windows.
