### ISSUE TITLE
ImportError: cannot import name 'Final' from 'typing' (/usr/lib/python3.7/typing.py)

### ISSUE THREAD

**Issue by DeFiFarmerJohn** [cyberjunky/3commas-cyber-bots#87]
I cannot run any of the scripts since today git pull and reboot.  I keep getting this error on every script.

root@ip-:~/3commas-cyber-bots# python3 ./trailingstoploss_tp.py
Traceback (most recent call last):
  File "./trailingstoploss_tp.py", line 13, in <module>
    from helpers.misc import check_deal, wait_time_interval
  File "/root/3commas-cyber-bots/helpers/misc.py", line 7, in <module>
    from constants.pair import PAIREXCLUDE_EXT
  File "/root/3commas-cyber-bots/constants/pair.py", line 2, in <module>
    from typing import Final
ImportError: cannot import name 'Final' from 'typing' (/usr/lib/python3.7/typing.py)

Status for services has problem too.
Any help is appreciated.

**Comment by DeFiFarmerJohn** [comment]
Problem was fixed by upgrading python.  Thank you.

**Comment by cyberjunky** [comment]
@DeFiFarmerJohn which version did you go to? We should be able to run on 3.7 so we have to replace the Final statement perhaps.
