### ISSUE TITLE
Add coinmarketcap max rank "requirement" to Altrank

### ISSUE THREAD

**Issue by pvdochtend** [cyberjunky/3commas-cyber-bots#89]
**Is your feature request related to a problem? Please describe.**
Currently I'm using the Altrank script. But there are also pairs like "SPELLBUSD" for example that only exists since 7-12-2021.
I don't want to have those kind of coins because they can go "to zero".
I think when we add an extra filter to the coin selection, for example Coinmarketcap rank < 150 then we can assume that they don't go to zero because of the total marketcap.

**Describe the solution you'd like**
What I described above. Since we already have the API around. I hope it can be easily added to the lunarcrush_pairs function where we also check for volume, altrank rank etc.

**Comment by cyberjunky** [comment]
Do you mean the cmc ranking value is in the lunarcrush data, or using the seperate data from coinmarketcap? The last one means we need to make it optional.
A bit short on time to check lunarcrush data set, so any help is welcome :)

**Comment by frontero** [comment]
I'm looking for the same feature as well. The script now chooses the coins based the altrank value and then the top x coins. What I would like to see is that it also chooses those coins, but then only if they are in the top x of the coinmarketcap order. So that a coin in the altrank is number 1, but in the coinmarketcap number 5000 i.e. that it wouldn't added that coin to the bot.

**Comment by amargedon** [comment]
For this to work, the different datasets need to be combined. So input from Altrank, GalaxyScore, CoinmarketCap ed needs to be collected, and then the user should be able to put in some configuration to get the desired list of pairs as output.

As these are currently all seperate scripts, and we have a lot of other requests/stuff already going on, it's not something I see happening in a short timeframe. Yes, I understand the value and it would be a good addition. Time however....
