### ISSUE TITLE
Error when character '%' in botname 

### ISSUE THREAD

**Issue by M1cha3l-2022** [cyberjunky/3commas-cyber-bots#99]
config.parser can not deal with single character '%' in botname. Solution is to replace % in botname with %%.

galaxyscore.py
_________________________________________________________________
      # Walk through all bots configured
        for thebot in thebotids:
            if not cfg.has_section(f"bot_{thebot}"):

                error, data = theapi.request(
                    entity="bots",
                    action="show",
                    action_id=str(thebot),
                )

               if data:
                    # Add new config section
                    
                    cfg[f"bot_{thebot}"] = {
                        "maxaltrankscore": default_maxaltrankscore,
                        "numberofpairs": default_numberofpairs,
                        "originalmaxdeals": int(data["max_active_deals"]),
                        "allowmaxdealchange": False,
==>                        "comment": data["name"].replace('%','%%'),
                    }
________________________________________________________________

**Comment by cyberjunky** [comment]
Thanks will update code soon!

**Comment by cyberjunky** [comment]
I have updated the code (took a bit longer to find some time) thanks again!
